### ISSUE TITLE
Error 52100 unable to connect.

### ISSUE THREAD

**Issue by ShinHaguchi56** [kuroppoi/entralinked#53] opened 2024-04-28 21:31 UTC
alrighty so I've went through everything i can think of error wise even enablng it on the defender firewall did nothing, I have to assume its an issue of the service or this itself otherwise I'm unsure what the hell i'm doing wrong.

**Comment by kuroppoi** [comment] 2024-04-28 22:59
Duplicate of #50 (I've commented there instead)

**Closed by kuroppoi** 2024-04-28 22:59 UTC
Labels: duplicate
