### ISSUE TITLE
What solution to use

### ISSUE THREAD

**Issue by pokemonfan6498** [kuroppoi/entralinked#46] opened 2024-03-16 15:55 UTC
i tried to launch the program at first it ran fine until it shown an error saying something like adress already in use i have log of it as evidence
[latest.log](https://github.com/kuroppoi/entralinked/files/14624255/latest.log)

**Comment by kuroppoi** [comment] 2024-03-19 15:08
Duplicate of #2, try to use the solution listed here:
https://github.com/kuroppoi/entralinked/wiki/Troubleshooting#address-already-in-use-bind

**Closed by kuroppoi** 2024-03-19 15:08 UTC

**Comment by pokemonfan6498** [comment] 2024-03-21 12:39
Alright got it

**Comment by pokemonfan6498** [comment] 2024-03-21 12:40
But does this thing requires any external accessories to work?

**Comment by pokemonfan6498** [comment] 2024-03-21 16:05
umm i don't have Host Network Service in services.msc
